# Generated by Django 3.0.8 on 2020-08-06 23:11

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pvp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolutionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=100)),
                ('evolution', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
    ]
